apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: hlt001-job-helmdoc-ingress-nginx-admission-create.yaml
- path: hlt001-job-helmdoc-ingress-nginx-admission-patch.yaml
- path: hlt002-job-helmdoc-ingress-nginx-admission-create.yaml
- path: hlt002-job-helmdoc-ingress-nginx-admission-patch.yaml
