package fix

import (
	"reflect"
	"strings"
	"testing"

	"github.com/belyaev-dev/helmdoc/internal/rules"
	_ "github.com/belyaev-dev/helmdoc/internal/rules/all"
	"github.com/belyaev-dev/helmdoc/internal/testutil/realcharts"
	"github.com/belyaev-dev/helmdoc/pkg/models"
	"sigs.k8s.io/yaml"
)

func TestPlanKustomizePatchesKeepsUnresolvedFindingsPending(t *testing.T) {
	tests := []struct {
		name          string
		ctx           rules.AnalysisContext
		finding       models.Finding
		wantReasonSub string
	}{
		{
			name: "missing rendered resource",
			ctx:  rules.AnalysisContext{},
			finding: models.Finding{
				RuleID:      "HLT001",
				Path:        "templates/admission-webhooks/job-patch/job-createSecret.yaml",
				Resource:    "Job/helmdoc-ingress-nginx-admission-create",
				Description: `container "create" in Job/helmdoc-ingress-nginx-admission-create has no livenessProbe.`,
			},
			wantReasonSub: "rendered resource lookup missed",
		},
		{
			name: "container name mismatch stays pending",
			ctx: rules.AnalysisContext{
				RenderedResources: map[string][]models.K8sResource{
					"templates/admission-webhooks/job-patch/job-createSecret.yaml": {
						newJobResource("helmdoc-ingress-nginx-admission-create", "other"),
					},
				},
			},
			finding: models.Finding{
				RuleID:      "HLT002",
				Path:        "templates/admission-webhooks/job-patch/job-createSecret.yaml",
				Resource:    "Job/helmdoc-ingress-nginx-admission-create",
				Description: `container "create" in Job/helmdoc-ingress-nginx-admission-create has no readinessProbe.`,
			},
			wantReasonSub: `does not include target container "create"`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			plan := PlanBundle(tt.ctx, []models.Finding{tt.finding})
			if len(plan.AppliedValuesFixes) != 0 {
				t.Fatalf("len(plan.AppliedValuesFixes) = %d, want 0", len(plan.AppliedValuesFixes))
			}
			if len(plan.KustomizePatches) != 0 {
				t.Fatalf("len(plan.KustomizePatches) = %d, want 0", len(plan.KustomizePatches))
			}
			if len(plan.PendingFindings) != 1 {
				t.Fatalf("len(plan.PendingFindings) = %d, want 1", len(plan.PendingFindings))
			}

			pending := plan.PendingFindings[0]
			if pending.Finding.RuleID != tt.finding.RuleID {
				t.Fatalf("pending rule = %q, want %q", pending.Finding.RuleID, tt.finding.RuleID)
			}
			if !strings.Contains(pending.Reason, "needs another fix path") {
				t.Fatalf("pending reason = %q, want original values-first reason preserved", pending.Reason)
			}
			if !strings.Contains(pending.Reason, tt.wantReasonSub) {
				t.Fatalf("pending reason = %q, want substring %q", pending.Reason, tt.wantReasonSub)
			}
		})
	}
}

func TestRenderKustomizePatchYAMLIncludesProvenanceComments(t *testing.T) {
	patch := sampleKustomizePatch(t, "HLT001", "templates/admission-webhooks/job-patch/job-createSecret.yaml", "Job/helmdoc-ingress-nginx-admission-create", "helmdoc-ingress-nginx-admission-create", "create")

	if got := KustomizePatchFileName(patch); got != "hlt001-job-helmdoc-ingress-nginx-admission-create.yaml" {
		t.Fatalf("KustomizePatchFileName() = %q, want %q", got, "hlt001-job-helmdoc-ingress-nginx-admission-create.yaml")
	}

	data, err := RenderKustomizePatchYAML(patch)
	if err != nil {
		t.Fatalf("RenderKustomizePatchYAML() error = %v", err)
	}

	text := string(data)
	for _, check := range []string{
		"# Generated by helmdoc fix.",
		"# File: kustomize/hlt001-job-helmdoc-ingress-nginx-admission-create.yaml",
		"# Apply this file from the generated kustomize/ overlay",
		"# Target resource: Job/helmdoc-ingress-nginx-admission-create",
		"# Target namespace: default",
		"# Provenance: HLT001 Job/helmdoc-ingress-nginx-admission-create @ templates/admission-webhooks/job-patch/job-createSecret.yaml",
		"# target container: create",
		"# planned patch: Add a conservative livenessProbe directly to the rendered workload container.",
		"# rule detail: container \"create\" in Job/helmdoc-ingress-nginx-admission-create has no livenessProbe.",
		"apiVersion: batch/v1",
		"kind: Job",
		"livenessProbe:",
	} {
		if !strings.Contains(text, check) {
			t.Fatalf("patch YAML missing %q\n%s", check, text)
		}
	}

	var rendered map[string]any
	if err := yaml.Unmarshal(data, &rendered); err != nil {
		t.Fatalf("yaml.Unmarshal(patch) error = %v\n%s", err, data)
	}

	if rendered["apiVersion"] != "batch/v1" {
		t.Fatalf("apiVersion = %#v, want %q", rendered["apiVersion"], "batch/v1")
	}
	if rendered["kind"] != "Job" {
		t.Fatalf("kind = %#v, want %q", rendered["kind"], "Job")
	}
	metadata := requireNestedMap(t, rendered, "metadata")
	if metadata["name"] != "helmdoc-ingress-nginx-admission-create" {
		t.Fatalf("metadata.name = %#v, want %q", metadata["name"], "helmdoc-ingress-nginx-admission-create")
	}
	if metadata["namespace"] != "default" {
		t.Fatalf("metadata.namespace = %#v, want %q", metadata["namespace"], "default")
	}

	spec := requireNestedMap(t, rendered, "spec")
	template := requireNestedMap(t, spec, "template")
	podSpec := requireNestedMap(t, template, "spec")
	containers, ok := podSpec["containers"].([]any)
	if !ok || len(containers) != 1 {
		t.Fatalf("containers = %#v, want one entry", podSpec["containers"])
	}
	container, ok := containers[0].(map[string]any)
	if !ok {
		t.Fatalf("containers[0] = %#v, want map[string]any", containers[0])
	}
	if container["name"] != "create" {
		t.Fatalf("container name = %#v, want %q", container["name"], "create")
	}
	if _, ok := container["livenessProbe"].(map[string]any); !ok {
		t.Fatalf("livenessProbe = %#v, want map[string]any", container["livenessProbe"])
	}
}

func TestRenderKustomizationYAML(t *testing.T) {
	fixture := realcharts.FixtureByID(t, "nginx-ingress")
	ctx := realcharts.AnalysisContext(t, fixture)
	plan := PlanBundle(ctx, rules.RunAll(ctx))

	data, err := RenderKustomizationYAML(plan)
	if err != nil {
		t.Fatalf("RenderKustomizationYAML() error = %v", err)
	}

	var doc struct {
		APIVersion string `json:"apiVersion"`
		Kind       string `json:"kind"`
		Patches    []struct {
			Path string `json:"path"`
		} `json:"patches"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("yaml.Unmarshal(kustomization) error = %v\n%s", err, data)
	}

	if doc.APIVersion != "kustomize.config.k8s.io/v1beta1" {
		t.Fatalf("apiVersion = %q, want %q", doc.APIVersion, "kustomize.config.k8s.io/v1beta1")
	}
	if doc.Kind != "Kustomization" {
		t.Fatalf("kind = %q, want %q", doc.Kind, "Kustomization")
	}

	gotPaths := make([]string, 0, len(doc.Patches))
	for _, patch := range doc.Patches {
		gotPaths = append(gotPaths, patch.Path)
	}
	wantPaths := []string{
		"hlt001-job-helmdoc-ingress-nginx-admission-create.yaml",
		"hlt001-job-helmdoc-ingress-nginx-admission-patch.yaml",
		"hlt002-job-helmdoc-ingress-nginx-admission-create.yaml",
		"hlt002-job-helmdoc-ingress-nginx-admission-patch.yaml",
	}
	if !reflect.DeepEqual(gotPaths, wantPaths) {
		t.Fatalf("patch paths = %#v, want %#v\n%s", gotPaths, wantPaths, data)
	}
}

func sampleKustomizePatch(t *testing.T, ruleID, path, resource, name, containerName string) KustomizePatch {
	t.Helper()

	description := `container "` + containerName + `" in ` + resource + ` has no livenessProbe.`
	if ruleID == "HLT002" {
		description = `container "` + containerName + `" in ` + resource + ` has no readinessProbe.`
	}
	finding := models.Finding{
		RuleID:      ruleID,
		Path:        path,
		Resource:    resource,
		Description: description,
	}
	target := ResourceRef{
		APIVersion: "batch/v1",
		Kind:       "Job",
		Name:       name,
		Namespace:  "default",
	}
	patchBody, summary, err := defaultKustomizePatchForFinding(finding, target, containerName)
	if err != nil {
		t.Fatalf("defaultKustomizePatchForFinding() error = %v", err)
	}

	return KustomizePatch{
		Finding:       finding,
		Target:        target,
		ContainerName: containerName,
		Patch:         patchBody,
		Summary:       summary,
	}
}

func newJobResource(name, containerName string) models.K8sResource {
	return models.K8sResource{
		APIVersion: "batch/v1",
		Kind:       "Job",
		Name:       name,
		Namespace:  "default",
		Raw: map[string]any{
			"spec": map[string]any{
				"template": map[string]any{
					"spec": map[string]any{
						"containers": []any{
							map[string]any{"name": containerName},
						},
					},
				},
			},
		},
	}
}
