package fix

import (
	"fmt"
	"sort"
	"strings"
	"unicode"

	"sigs.k8s.io/yaml"
)

const KustomizeDirName = "kustomize"

type kustomizationFile struct {
	APIVersion string                    `json:"apiVersion"`
	Kind       string                    `json:"kind"`
	Patches    []kustomizationPatchEntry `json:"patches"`
}

type kustomizationPatchEntry struct {
	Path string `json:"path"`
}

// KustomizePatchFileName derives a deterministic patch filename for one planned patch.
func KustomizePatchFileName(patch KustomizePatch) string {
	parts := []string{
		slugKustomizeFilenamePart(patch.Finding.RuleID),
		slugKustomizeFilenamePart(patch.Target.Kind),
		slugKustomizeFilenamePart(patch.Target.Name),
	}
	if namespace := strings.TrimSpace(patch.Target.Namespace); namespace != "" && namespace != "default" {
		parts = append(parts, slugKustomizeFilenamePart(namespace))
	}

	filtered := make([]string, 0, len(parts))
	for _, part := range parts {
		if part != "" {
			filtered = append(filtered, part)
		}
	}
	if len(filtered) == 0 {
		return "patch.yaml"
	}
	return strings.Join(filtered, "-") + ".yaml"
}

// KustomizePatchRelativePath returns the bundle-relative path used in README and kustomization output.
func KustomizePatchRelativePath(patch KustomizePatch) string {
	return KustomizeDirName + "/" + KustomizePatchFileName(patch)
}

// RenderKustomizePatchYAML serializes one strategic-merge patch document.
func RenderKustomizePatchYAML(patch KustomizePatch) ([]byte, error) {
	if err := validateBundlePlan(BundlePlan{KustomizePatches: []KustomizePatch{patch}}); err != nil {
		return nil, err
	}

	data, err := yaml.Marshal(patch.Patch)
	if err != nil {
		return nil, fmt.Errorf("marshal kustomize patch %s: %w", KustomizePatchFileName(patch), err)
	}
	if len(data) == 0 || data[len(data)-1] != '\n' {
		data = append(data, '\n')
	}
	return prependCommentBlock(kustomizePatchProvenanceCommentLines(patch), data), nil
}

// RenderKustomizationYAML renders the deterministic kustomization manifest for all planned patches.
func RenderKustomizationYAML(plan BundlePlan) ([]byte, error) {
	plan = normalizedBundlePlan(plan)
	if err := validateBundlePlan(plan); err != nil {
		return nil, err
	}

	fileNames := make([]string, 0, len(plan.KustomizePatches))
	seen := make(map[string]struct{}, len(plan.KustomizePatches))
	for _, patch := range plan.KustomizePatches {
		fileName := KustomizePatchFileName(patch)
		if _, exists := seen[fileName]; exists {
			return nil, fmt.Errorf("duplicate kustomize patch filename %q", fileName)
		}
		seen[fileName] = struct{}{}
		fileNames = append(fileNames, fileName)
	}
	sort.Strings(fileNames)

	doc := kustomizationFile{
		APIVersion: "kustomize.config.k8s.io/v1beta1",
		Kind:       "Kustomization",
		Patches:    make([]kustomizationPatchEntry, 0, len(fileNames)),
	}
	for _, fileName := range fileNames {
		doc.Patches = append(doc.Patches, kustomizationPatchEntry{Path: fileName})
	}

	data, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("marshal kustomization.yaml: %w", err)
	}
	if len(data) == 0 || data[len(data)-1] != '\n' {
		data = append(data, '\n')
	}
	return data, nil
}

func kustomizePatchProvenanceCommentLines(patch KustomizePatch) []string {
	lines := []string{
		"Generated by helmdoc fix.",
		"File: " + KustomizePatchRelativePath(patch),
		"Apply this file from the generated kustomize/ overlay after rendering the chart manifests.",
		fmt.Sprintf("Target resource: %s/%s", patch.Target.Kind, patch.Target.Name),
	}
	if namespace := strings.TrimSpace(patch.Target.Namespace); namespace != "" {
		lines = append(lines, "Target namespace: "+namespace)
	}
	lines = append(lines, fmt.Sprintf("Provenance: %s", plainFindingLocation(patch.Finding)))
	if patch.ContainerName != "" {
		lines = append(lines, "target container: "+patch.ContainerName)
	}
	if summary := normalizeSentence(patch.Summary); summary != "" {
		lines = append(lines, "planned patch: "+summary)
	}
	if description := normalizeSentence(patch.Finding.Description); description != "" {
		lines = append(lines, "rule detail: "+description)
	}
	return lines
}

func slugKustomizeFilenamePart(value string) string {
	var builder strings.Builder
	builder.Grow(len(value))

	lastWasHyphen := false
	for _, r := range value {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			builder.WriteRune(unicode.ToLower(r))
			lastWasHyphen = false
		case !lastWasHyphen:
			builder.WriteByte('-')
			lastWasHyphen = true
		}
	}

	return strings.Trim(builder.String(), "-")
}
