version: 2

project_name: helmdoc

release:
  github:
    owner: belyaev-dev
    name: helmdoc

snapshot:
  version_template: "0.0.0-snapshot-{{ .ShortCommit }}"

changelog:
  disable: true

builds:
  - id: helmdoc
    main: .
    binary: helmdoc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X github.com/belyaev-dev/helmdoc/cmd/helmdoc.version={{ .Tag }}
        -X github.com/belyaev-dev/helmdoc/cmd/helmdoc.commit={{ .Commit }}
        -X github.com/belyaev-dev/helmdoc/cmd/helmdoc.date={{ .Date }}

archives:
  - id: binaries
    ids:
      - helmdoc
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

brews:
  - ids:
      - binaries
    repository:
      owner: belyaev-dev
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: "https://github.com/belyaev-dev/helmdoc"
    description: "Analyze and fix Helm charts"
    license: MIT
    commit_msg_template: "Brew formula update for {{ .ProjectName }} {{ .Tag }}"
    install: |
      bin.install "helmdoc"
    test: |
      system "#{bin}/helmdoc", "version"

dockers:
  - ids:
      - helmdoc
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/belyaev-dev/helmdoc:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/belyaev-dev/helmdoc"
  - ids:
      - helmdoc
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/belyaev-dev/helmdoc:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/belyaev-dev/helmdoc"

docker_manifests:
  - name_template: "ghcr.io/belyaev-dev/helmdoc:{{ .Version }}"
    image_templates:
      - "ghcr.io/belyaev-dev/helmdoc:{{ .Version }}-amd64"
      - "ghcr.io/belyaev-dev/helmdoc:{{ .Version }}-arm64"
  - name_template: "ghcr.io/belyaev-dev/helmdoc:latest"
    image_templates:
      - "ghcr.io/belyaev-dev/helmdoc:{{ .Version }}-amd64"
      - "ghcr.io/belyaev-dev/helmdoc:{{ .Version }}-arm64"
