package helmdoc

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/belyaev-dev/helmdoc/internal/testutil/realcharts"
)

func TestFixCommandWritesBundle(t *testing.T) {
	fixture := realcharts.FixtureByID(t, "nginx-ingress")
	chartPath := realcharts.FixturePath(t, fixture)
	outputDir := filepath.Join(t.TempDir(), "bundle")

	stdout, stderr, err := executeFixCommand(t, "--output-dir", outputDir, chartPath)
	if err != nil {
		t.Fatalf("executeFixCommand(%q) error = %v\nstderr:\n%s\nstdout:\n%s", chartPath, err, stderr, stdout)
	}
	if stderr != "" {
		t.Fatalf("stderr = %q, want empty", stderr)
	}
	for _, want := range []string{
		"Wrote helmdoc fix bundle to ",
		"values-overrides.yaml",
		"README.md",
		"kustomize/kustomization.yaml",
	} {
		if !strings.Contains(stdout, want) {
			t.Fatalf("stdout missing %q\n%s", want, stdout)
		}
	}

	valuesPath := filepath.Join(outputDir, "values-overrides.yaml")
	valuesData := requireNonEmptyFile(t, valuesPath)
	for _, want := range []string{
		"# Generated by helmdoc fix.",
		"# - SEC003 Deployment/helmdoc-ingress-nginx-controller @ templates/controller-deployment.yaml -> controller.image.readOnlyRootFilesystem",
		"controller:",
		"readOnlyRootFilesystem: true",
		"autoscaling:",
	} {
		if !strings.Contains(valuesData, want) {
			t.Fatalf("values-overrides.yaml missing %q\n%s", want, valuesData)
		}
	}

	readmePath := filepath.Join(outputDir, "README.md")
	readmeData := requireNonEmptyFile(t, readmePath)
	for _, want := range []string{
		"# Helmdoc fix bundle",
		"## Applied values fixes (9)",
		"## Kustomize patches (4)",
		"## Advisory-only findings (0)",
		"## Findings pending another fix path (0)",
		"kustomize/hlt001-job-helmdoc-ingress-nginx-admission-create.yaml",
		"kustomize/hlt002-job-helmdoc-ingress-nginx-admission-patch.yaml",
	} {
		if !strings.Contains(readmeData, want) {
			t.Fatalf("README.md missing %q\n%s", want, readmeData)
		}
	}

	kustomizeDir := filepath.Join(outputDir, "kustomize")
	entries, err := os.ReadDir(kustomizeDir)
	if err != nil {
		t.Fatalf("os.ReadDir(%q) error = %v", kustomizeDir, err)
	}
	if len(entries) != 5 {
		t.Fatalf("len(kustomize entries) = %d, want 5", len(entries))
	}
	for _, relPath := range []string{
		"kustomize/kustomization.yaml",
		"kustomize/hlt001-job-helmdoc-ingress-nginx-admission-create.yaml",
		"kustomize/hlt001-job-helmdoc-ingress-nginx-admission-patch.yaml",
		"kustomize/hlt002-job-helmdoc-ingress-nginx-admission-create.yaml",
		"kustomize/hlt002-job-helmdoc-ingress-nginx-admission-patch.yaml",
	} {
		data := requireNonEmptyFile(t, filepath.Join(outputDir, filepath.FromSlash(relPath)))
		if relPath == "kustomize/kustomization.yaml" {
			for _, want := range []string{"apiVersion: kustomize.config.k8s.io/v1beta1", "kind: Kustomization"} {
				if !strings.Contains(data, want) {
					t.Fatalf("%s missing %q\n%s", relPath, want, data)
				}
			}
			continue
		}
		if !strings.Contains(data, "# Generated by helmdoc fix.") {
			t.Fatalf("%s missing provenance header\n%s", relPath, data)
		}
	}
}

func TestFixCommandRequiresOutputDir(t *testing.T) {
	fixture := realcharts.FixtureByID(t, "nginx-ingress")
	chartPath := realcharts.FixturePath(t, fixture)

	stdout, stderr, err := executeFixCommand(t, chartPath)
	if err == nil {
		t.Fatal("executeFixCommand() error = nil, want non-nil")
	}
	if stdout != "" {
		t.Fatalf("stdout = %q, want empty", stdout)
	}
	if !strings.Contains(err.Error(), "required flag(s) \"output-dir\" not set") {
		t.Fatalf("error = %q, want required output-dir failure", err)
	}
	if !strings.Contains(stderr, "required flag(s) \"output-dir\" not set") {
		t.Fatalf("stderr = %q, want required output-dir failure", stderr)
	}
}

func TestRootCommandRegistersFix(t *testing.T) {
	root := newRootCommand()

	want := map[string]bool{"version": true, "scan": true, "fix": true}
	for _, cmd := range root.Commands() {
		delete(want, cmd.Name())
	}
	if len(want) != 0 {
		t.Fatalf("root command missing subcommands: %#v", want)
	}
}

func executeFixCommand(t *testing.T, args ...string) (stdout string, stderr string, err error) {
	t.Helper()

	cmd := newFixCommand()
	var stdoutBuf bytes.Buffer
	var stderrBuf bytes.Buffer
	cmd.SetOut(&stdoutBuf)
	cmd.SetErr(&stderrBuf)
	cmd.SetArgs(args)

	err = cmd.Execute()
	return stdoutBuf.String(), stderrBuf.String(), err
}

func requireNonEmptyFile(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("os.ReadFile(%q) error = %v", path, err)
	}
	text := string(data)
	if strings.TrimSpace(text) == "" {
		t.Fatalf("%s was empty", path)
	}
	return text
}
